### ISSUE TITLE
When we use DictateButton component in form, on clicking this button, submit handler is being called.

### ISSUE THREAD

**Issue by niranjan241** [compulim/react-dictate-button#39]
https://github.com/compulim/react-dictate-button/blob/6b4fe72b18532ce1cfb6bca63139114ec7e2b81d/packages/component/src/DictateButton.js#L51

When button is used without type, by default it takes it as type "submit" and when dictate button is used in forms, it is calling submit handler. In order to avoid this issue, Can you please add type as button to it ?

**Comment by compulim** [comment]
Working on it. This will be fixed very soon.
